package indexing

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"io"
	"os"
	"strings"
	"unicode"
	"unicode/utf8"
)

// computeContentHash calculates a deterministic SHA-256 hex digest for a file.
func computeContentHash(absPath string) (string, int64, error) {
	f, err := os.Open(absPath)
	if err != nil {
		return "", 0, err
	}
	defer f.Close()

	hasher := sha256.New()
	size, err := io.Copy(hasher, f)
	if err != nil {
		return "", 0, err
	}

	return hex.EncodeToString(hasher.Sum(nil)), size, nil
}

// inspectFileContent inspects encoding, line endings, and structural line counts.
func inspectFileContent(absPath string) (EncodingType, LineEndingType, int, int, int, error) {
	data, err := os.ReadFile(absPath)
	if err != nil {
		return EncodingUnknown, LineEndingUnknown, 0, 0, 0, err
	}

	if len(data) == 0 {
		return EncodingASCII, LineEndingUnknown, 0, 0, 0, nil
	}

	// 1. Detect Encoding
	encoding := detectEncoding(data)
	if encoding == EncodingUnknown || encoding == EncodingInvalid {
		return encoding, LineEndingUnknown, 0, 0, 0, nil
	}

	// 2. Detect Line Endings & Count Lines
	lineEnding := detectLineEndings(data)
	totalLines, blankLines, commentLines := countStructuralLines(data)

	return encoding, lineEnding, totalLines, blankLines, commentLines, nil
}

func detectEncoding(data []byte) EncodingType {
	if len(data) >= 2 {
		if data[0] == 0xFF && data[1] == 0xFE {
			return EncodingUTF16LE
		}
		if data[0] == 0xFE && data[1] == 0xFF {
			return EncodingUTF16BE
		}
	}

	// Check for binary null bytes in initial sample (up to 8KB)
	sampleSize := len(data)
	if sampleSize > 8192 {
		sampleSize = 8192
	}
	if bytes.IndexByte(data[:sampleSize], 0x00) != -1 {
		return EncodingUnknown
	}

	if utf8.Valid(data) {
		isASCII := true
		for _, b := range data[:sampleSize] {
			if b > 127 {
				isASCII = false
				break
			}
		}
		if isASCII {
			return EncodingASCII
		}
		return EncodingUTF8
	}

	return EncodingInvalid
}

func detectLineEndings(data []byte) LineEndingType {
	var hasCRLF, hasLF, hasCR bool

	for i := 0; i < len(data); i++ {
		if data[i] == '\r' {
			if i+1 < len(data) && data[i+1] == '\n' {
				hasCRLF = true
				i++ // skip LF
			} else {
				hasCR = true
			}
		} else if data[i] == '\n' {
			hasLF = true
		}
	}

	typesFound := 0
	if hasCRLF {
		typesFound++
	}
	if hasLF {
		typesFound++
	}
	if hasCR {
		typesFound++
	}

	if typesFound > 1 {
		return LineEndingMixed
	}
	if hasCRLF {
		return LineEndingCRLF
	}
	if hasLF {
		return LineEndingLF
	}
	if hasCR {
		return LineEndingCR
	}

	return LineEndingUnknown
}

func countStructuralLines(data []byte) (int, int, int) {
	scanner := bufio.NewScanner(bytes.NewReader(data))
	var total, blank, comments int
	var inBlockComment bool

	for scanner.Scan() {
		total++
		line := strings.TrimSpace(scanner.Text())

		if line == "" {
			blank++
			continue
		}

		if inBlockComment {
			comments++
			if strings.Contains(line, "*/") {
				inBlockComment = false
			}
			continue
		}

		if strings.HasPrefix(line, "/*") {
			comments++
			if !strings.Contains(line, "*/") {
				inBlockComment = true
			}
			continue
		}

		if strings.HasPrefix(line, "//") || strings.HasPrefix(line, "#") {
			comments++
			continue
		}
	}

	_ = scanner.Err() // scanner on bytes.NewReader does not produce IO errors

	return total, blank, comments
}

// detectGenerationStatus checks for standard code generator markers.
func detectGenerationStatus(absPath string) GenerationStatus {
	f, err := os.Open(absPath)
	if err != nil {
		return GenerationStatusUnknown
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	lineCount := 0

	for scanner.Scan() {
		lineCount++
		if lineCount > 50 {
			break
		}
		line := strings.TrimSpace(scanner.Text())

		if strings.Contains(line, "Code generated") && strings.Contains(line, "DO NOT EDIT") {
			return GenerationStatusGenerated
		}
		if strings.Contains(line, "@generated") || strings.Contains(line, "AUTOGENERATED BY") {
			return GenerationStatusGenerated
		}
	}

	if err := scanner.Err(); err != nil {
		return GenerationStatusUnknown
	}

	return GenerationStatusHandwritten
}

// inspectGoSourceFile extracts package name, doc comment, imports, and top-level exports from a Go file.
func inspectGoSourceFile(absPath string) (string, string, []string, []string, error) {
	f, err := os.Open(absPath)
	if err != nil {
		return "", "", nil, nil, err
	}
	defer f.Close()

	var (
		pkgName   string
		docLines  []string
		imports   []string
		exports   []string
		inImport  bool
		foundPkg  bool
		accumDocs []string
	)

	scanner := bufio.NewScanner(f)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Accumulate comments before package declaration as package doc
		if !foundPkg {
			if strings.HasPrefix(line, "//") {
				accumDocs = append(accumDocs, strings.TrimSpace(strings.TrimPrefix(line, "//")))
				continue
			}
			if strings.HasPrefix(line, "/*") && strings.HasSuffix(line, "*/") {
				c := strings.TrimSuffix(strings.TrimPrefix(line, "/*"), "*/")
				accumDocs = append(accumDocs, strings.TrimSpace(c))
				continue
			}
		}

		if strings.HasPrefix(line, "package ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				pkgName = parts[1]
				foundPkg = true
				docLines = accumDocs
			}
			continue
		}

		if !foundPkg {
			accumDocs = nil
			continue
		}

		// Handle imports
		if line == "import (" {
			inImport = true
			continue
		}
		if inImport && line == ")" {
			inImport = false
			continue
		}
		if inImport {
			clean := strings.Trim(line, " \t\"`")
			if clean != "" && !strings.HasPrefix(clean, "//") {
				parts := strings.Fields(clean)
				if len(parts) > 0 {
					impPath := strings.Trim(parts[len(parts)-1], "\"'`")
					imports = append(imports, impPath)
				}
			}
			continue
		}
		if strings.HasPrefix(line, "import ") {
			clean := strings.TrimPrefix(line, "import ")
			clean = strings.Trim(clean, " \t\"`")
			if idx := strings.Index(clean, "\""); idx != -1 {
				clean = clean[idx+1:]
				if endIdx := strings.Index(clean, "\""); endIdx != -1 {
					imports = append(imports, clean[:endIdx])
				}
			}
			continue
		}

		// Handle top-level exports
		if strings.HasPrefix(line, "func ") {
			sub := strings.TrimPrefix(line, "func ")
			if strings.HasPrefix(sub, "(") {
				// Method receiver e.g. func (r *Recv) MethodName(...)
				if idx := strings.Index(sub, ")"); idx != -1 {
					sub = strings.TrimSpace(sub[idx+1:])
				}
			}
			if idx := strings.Index(sub, "("); idx != -1 {
				ident := strings.TrimSpace(sub[:idx])
				if ident != "" {
					r := []rune(ident)[0]
					if unicode.IsUpper(r) {
						exports = append(exports, ident)
					}
				}
			}
		} else {
			prefixes := []string{"type ", "var ", "const "}
			for _, prefix := range prefixes {
				if strings.HasPrefix(line, prefix) {
					sub := strings.TrimPrefix(line, prefix)
					fields := strings.Fields(sub)
					if len(fields) > 0 {
						ident := strings.Trim(fields[0], "(* \t\r\n")
						if ident != "" {
							r := []rune(ident)[0]
							if unicode.IsUpper(r) {
								exports = append(exports, ident)
							}
						}
					}
					break
				}
			}
		}
	}

	if err := scanner.Err(); err != nil {
		return "", "", nil, nil, err
	}

	doc := strings.Join(docLines, "\n")
	return pkgName, doc, imports, exports, nil
}
